name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build --no-configuration-cache
      
    - name: Build Shadow JAR
      run: ./gradlew shadowJar --no-configuration-cache
      
    - name: Test CLI
      run: java -jar build/libs/ktfmt-cli-*.jar --version
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ktfmt-cli-jar
        path: build/libs/ktfmt-cli-*.jar
        retention-days: 30