name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build Shadow JAR
      run: ./gradlew shadowJar --no-configuration-cache
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Test CLI
      run: java -jar build/libs/ktfmt-cli-*.jar --version
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## ktfmt-cli ${{ steps.get_version.outputs.VERSION }}
          
          ### Changes
          - See commit history for detailed changes
          
          ### Usage
          Download the JAR file and run:
          ```bash
          java -jar ktfmt-cli-*.jar --help
          ```
          
          ### Example
          ```bash
          java -jar ktfmt-cli-*.jar "**/*.kt"
          ```
          
        files: |
          build/libs/ktfmt-cli-*.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}